### ISSUE TITLE
icon and name mess up when scroll up or down

### ISSUE THREAD

**Issue by ZhuZhengyi** [weirongxu/coc-explorer#306] opened 2020-11-09 14:22 UTC
: CocInfos
---

## versions

vim version: NVIM v0.5.0-nightly
node version: v14.0.0
coc.nvim version: 0.0.78-285a133071
coc.nvim directory: /Users/xxx/.zvt/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Output channel: explorer

![](https://gitee.com/justice/gitnote-img-bed/raw/master/2020/11/09-22-14-57-2020-11-09-22-14-52-image.png)

![](https://gitee.com/justice/gitnote-img-bed/raw/master/2020/11/09-22-30-41-2020-11-09-22-30-36-image.png)

**Comment by weirongxu** [comment] 2020-11-09 15:00
`set ambiwidth=single`

Duplicate of #238

**Closed by weirongxu** 2020-11-09 15:00 UTC
Labels: bug
