### ISSUE TITLE
in-place file operations

### ISSUE THREAD

**Issue by GopherJ** [weirongxu/coc-explorer#390] opened 2021-02-12 11:06 UTC
currently when we do some file operations on the file that's being editting, it's a pain.

![Peek 2021-02-12 19-03](https://user-images.githubusercontent.com/33961674/107760777-4748a600-6d65-11eb-9e71-a89deaac0ce6.gif)

as you can see from the gif, after renaming the file, and load it again, coc-explorer switched position to the right side, I have to close and re-open it.

**Comment by GopherJ** [comment] 2021-02-12 11:08
I would expect:

- `rename` can happen in place, aotomatically reload it with new name
- `delete` can by default load previous buffer

**Comment by weirongxu** [comment] 2021-02-16 17:07
Duplicate of #382, #279

**Closed by weirongxu** 2021-02-16 17:07 UTC
