### ISSUE TITLE
big problems with keyMappings

### ISSUE THREAD

**Issue by 4volodin** [weirongxu/coc-explorer#231] opened 2020-07-13 14:25 UTC
I am using key mappings in vim:
_nmap j gj
nmap k gk_
because it's convinient
and when I am pressing j or k I can't set cursor on files
and remaping gk, gj in coc-settings.json isn't helping
 it 's so bad
I would recomend you to use for remapping, for example
expandablePrev: keyMapHere
then I can assign 
expandablePrev: gi

**Comment by weirongxu** [comment] 2020-07-13 16:34
Duplicate of #201

**Closed by weirongxu** 2020-07-13 16:34 UTC
Labels: bug

**Comment by weirongxu** [comment] 2020-07-13 16:36
You can cancel the default keyMappings `"explorer.keyMappings": {"gk": false, "gj": false}`
