### ISSUE TITLE
explorer.file.autoReveal has been deprecated, please use explorer.file.reveal.auto instead of it

### ISSUE THREAD

**Issue by notthebee** [weirongxu/coc-explorer#550] opened 2022-11-29 07:33 UTC
**Describe the bug**

I get the following error message in neovim when opening coc-explorer: 
`explorer.file.autoReveal has been deprecated, please use explorer.file.reveal.auto instead of it`

However, I don't have the `explorer.file.autoReveal` option in my coc-settings.json, and setting the `explorer.file.reveal.auto` doesn't solve the problem either.

**Result from CocInfo**

```
## versions

vim version: NVIM v0.7.2
node version: v19.1.0
coc.nvim version: 0.0.82-9df40d3 2022-11-29 02:40:09 +0800
coc.nvim directory: /Users/[redacted]/.local/share/nvim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2022-11-29T08:28:00.575 INFO (pid:44080) [plugin] - coc.nvim initialized with node: v19.1.0 after 185
2022-11-29T08:28:00.811 INFO (pid:44080) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_15_2_coc_helper_1',
  'BufWipeout',
  1
]
2022-11-29T08:28:00.811 INFO (pid:44080) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_15_2_explorer_2',
  'BufWipeout',
  1
]
2022-11-29T08:28:01.016 INFO (pid:44080) [attach] - receive notification: runCommand [ 'explorer' ]
2022-11-29T08:28:01.039 INFO (pid:44080) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_15_2_coc_helper_1',
  'BufDelete',
  3
]
2022-11-29T08:28:01.039 INFO (pid:44080) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_15_2_explorer_2',
  'BufDelete',
  3
]
2022-11-29T08:29:04.599 INFO (pid:44080) [attach] - Request action: commandList [ 'un', 'CocCommand un', 13 ]
2022-11-29T08:29:04.781 INFO (pid:44080) [attach] - Request action: commandList [ 'un', 'CocCommand un', 13 ]
2022-11-29T08:30:18.011 INFO (pid:44080) [attach] - receive notification: showInfo []
2022-11-29T08:30:18.021 INFO (pid:44080) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_15_2_coc_helper_1',
  'BufDelete',
  4
]
2022-11-29T08:30:18.021 INFO (pid:44080) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_15_2_explorer_2',
  'BufDelete',
  4
]
2022-11-29T08:30:28.846 INFO (pid:44080) [attach] - receive notification: runCommand [ 'explorer' ]
2022-11-29T08:30:30.488 INFO (pid:44080) [attach] - receive notification: runCommand [ 'explorer' ]
2022-11-29T08:30:32.593 INFO (pid:44080) [attach] - receive notification: runCommand [ 'explorer' ]
2022-11-29T08:30:34.982 INFO (pid:44080) [attach] - receive notification: showInfo []
```

**Steps to reproduce**

1. execute `nvim`
2. `:CocCommand explorer`
3. See error

**Expected behavior**

coc-explorer opens with no error message

**Screenshots**

N/A

**Additional context**
None

**Comment by weirongxu** [comment] 2022-11-29 07:47
Duplicate of #547

**Closed by weirongxu** 2022-11-29 07:47 UTC
Labels: bug
