### ISSUE TITLE
Workspace argument support

### ISSUE THREAD

**Issue by andyrichardson** [weirongxu/coc-explorer#497] opened 2021-12-24 13:33 UTC
# About

Hi there, first off, thanks for making this!

It would be dope if workspace root support worked out of the box! I've been looking into [root strategies](https://github.com/weirongxu/coc-explorer#--root-strategies-root-strategies) but can't seem to get functionality that is default on other explorers (see below).

# Reproduction(s)

### Reproduction

 - Run `nvim /path/to/dir`

### Result

 - netrw explorer pane in `/path/to/dir`

### Reproduction

 - Install nerdtree
 - Run `nvim /path/to/dir`

### Result

 - nerdtree explorer pane in `/path/to/dir`
 - closing and opening the explorer maintains the location

### Reproduction

 - Install coc explorer
 - Run `nvim /path/to/dir`

### Result

 - **netrw** explorer pane in `/path/to/dir`
 - opening coc explorer opens the working directory (not `/path/to/dir`)

### Expected

 - coc explorer pane in `/path/to/dir`
 - opening coc explorer keeps the previous workspace root

**Comment by FahimAnayet** [comment] 2022-01-04 06:25
Put this in your init.vim file. It will work as expected.
```
"will open coc-explorer rather than netrw
augroup MyCocExplorer
  autocmd!
  autocmd VimEnter * sil! au! FileExplorer *
  autocmd BufEnter * let d = expand('%') | if isdirectory(d) | silent! bd | exe 'CocCommand explorer ' . d | endif
augroup END
```

**Comment by weirongxu** [comment] 2022-01-04 07:16
Duplicate of #123

**Closed by weirongxu** 2022-01-04 07:16 UTC
Labels: question
