### ISSUE TITLE
Head of file in explorer.previewAction

### ISSUE THREAD

**Issue by dderjoel** [weirongxu/coc-explorer#215] opened 2020-06-16 00:38 UTC
Hi,

I'd really like to have the first (say 10) lines of a file in the explorer.previewAction.Hover floating window thing.

1. I don't see any config option of that in the current Readme.md . (cant see where i could possibly change e.g the order of the lines in the floating windows)
1. Also I don't see any options for [content] or [head 10] or similar.

Please, if I just cannot find the locations in the docu, point it to me, else, if that's a feature-request, I'd be happy to submit a pull request.

**Comment by dderjoel** [comment] 2020-06-16 00:46
I'm sorry, --file-child-labeling-template <template> is what I was looking for. Maybe one could add a small note in the Readme 'The floating hover preview uses --file-child-labeling-template <template> as the options'.

However, I think there is still the feature-request of having the first lines in the content window as well.

**Comment by weirongxu** [comment] 2020-06-16 03:11
Duplicate of #71

**Closed by weirongxu** 2020-06-16 03:11 UTC
Labels: feature_request
