### ISSUE TITLE
Can't open coc-explorer due to detecting current working directory incorrectly

### ISSUE THREAD

**Issue by spindensity** [weirongxu/coc-explorer#267] opened 2020-09-11 16:52 UTC
## Steps to reproduce: the bug

1. Create directory `C:\test\test-coc-explorer`;
2. Add the following settings to `.vimrc`:

```vim
autocmd VimEnter * chdir C:\test\
```

3. Open vim from `C:\` root directory:

```bat
cd C:\
vim
```

4. Execute the following commands in vim:

```vim
:cd test-coc-explorer
:CocCommand explorer
```

5. The error happens: with the following message:

```log
[coc.nvim]: ENOENT: no such file or directory, scandir 'C:\test-coc-explorer'
```

## Environment

* OS: Windows 10 64bit;
* Vim: 8.2;
* coc-explorer: 0.7.31.

**Comment by weirongxu** [comment] 2020-09-18 18:22
Sorry for late, I can't reproduce this, what is the result of `:pwd` after cd `test-coc-explorer`?

**Comment by spindensity** [comment] 2020-09-18 19:03
> Sorry for late, I can't reproduce this, what is the result of `:pwd` after `:cd test-coc-explorer`?

Thanks for your reply.

1. After opening vim immediately, the result of `pwd` is `C:\test`, because the setting `autocmd VimEnter * chdir C:\test\ ` change the current working directory automatically;
2. After `:cd test-coc-explorer`, the result of `pwd` is `C:\test\test-coc-explorer`, and it's reasonable;
3. But we open vim from `C:\` directory, and it seems that `coc-explorer` isn't aware of the action binding to `VimEnter` event, and treats `C:\` rather than `C:\test` as the current working directory after entering vim. After `:cd test-coc-explorer`, the correct current working directory should be `C:\test\test-coc-explorer` as `pwd` shows, `coc-explorer` tries to open `C:\test-coc-explorer` rather than `C:\test\test-coc-explorer` and the error happens.

Now I use the following mapping:
```vim
nnoremap <silent><nowait> <space>f  :<C-u><C-r>=printf("CocCommand explorer %s",
            \ fnameescape(getcwd()))<CR><CR>
```
instead of
```vim
nnoremap <silent><nowait> <space>f  :<C-u>CocCommand explorer<CR>
```
as a workaround.

**Comment by weirongxu** [comment] 2020-09-18 19:08
Can I see the result of your `CocCommand workspace.workspaceFolders`? Because coc-explorer will use `workspace.rootPath` first https://github.com/weirongxu/coc-explorer#root-uri

**Comment by spindensity** [comment] 2020-09-18 19:23
> Can I see the result of your `:CocCommand workspace.workspaceFolders`? Because coc-explorer will use `workspace.rootPath` first https://github.com/weirongxu/coc-explorer#root-uri

## After entering vim immediately

The result of `:pwd` is `c:\test`:
![Snipaste_2020-09-19_03-15-56](https://user-images.githubusercontent.com/33576822/93636632-d9eb5000-fa26-11ea-9083-b0ee1da487e2.png)

The result of `:CocCommand workspace.workspaceFolders` is empty:
![Snipaste_2020-09-19_03-16-31](https://user-images.githubusercontent.com/33576822/93636702-f5565b00-fa26-11ea-968e-cc37a82333d9.png)

## After `cd test-coc-explorer`

The result of `pwd` is `c:\test\test-coc-explorer`:
![Snipaste_2020-09-19_03-16-49](https://user-images.githubusercontent.com/33576822/93636815-2171dc00-fa27-11ea-8398-45e4acd05ae0.png)

The result of `:CocCommand workspace.workspaceFolders` is still empty:
![Snipaste_2020-09-19_03-17-15](https://user-images.githubusercontent.com/33576822/93636890-40706e00-fa27-11ea-8c9c-ed9e5e82a248.png)

## The result of `:CocCommand explorer`
![Snipaste_2020-09-19_03-23-03](https://user-images.githubusercontent.com/33576822/93637002-731a6680-fa27-11ea-88fb-7555e447f9ed.png)

**Comment by weirongxu** [comment] 2020-09-19 05:46
Fixed in latest coc.nvim https://github.com/neoclide/coc.nvim/pull/2358

**Closed by weirongxu** 2020-09-19 05:46 UTC
Labels: bug
