### ISSUE TITLE
Will not redraw 

### ISSUE THREAD

**Issue by jobannon** [weirongxu/coc-explorer#62] opened 2019-12-16 06:00 UTC
I have coc-explorer mapped to 
nnoremap <Leader>t :CocCommand explorer<CR>

when I call it initially, it works as expected.  However, when I toggle the window away, and re-toggle, it redraws as seen below `^C120^D+^C120^D+^C120^D+^C120^D+^C120^D+" .  a related issue on https://gitter.im/neoclide/coc.nvim?at=5db181e7a03ae1584ffe25ad

![image](https://user-images.githubusercontent.com/16090626/70882952-a870c000-1f8e-11ea-8761-27b22bd41add.png)

**Comment by jobannon** [comment] 2019-12-16 06:01
I think that this behavior has to do with redraw but now sure....

**Comment by weirongxu** [comment] 2019-12-16 06:10
> However, when I toggle the window away, and re-toggle

Does this appear every time? 
If it does, can you provide vim version information (`:CocInfo`) and log (`:CocOpenLog`)?

**Comment by jobannon** [comment] 2019-12-16 06:16
let g:indentLine_fileTypeExclude = ['coc-explorer']
  let g:indentLine_fileTypeExclude = ['coc']
  autocmd FileType coc IndentLinesToggle
 have tried both of these to correct of this ... Although not sure if I have the syntax correct... 

view from 
  
![image](https://user-images.githubusercontent.com/16090626/70883610-c17a7080-1f90-11ea-8c92-1218bf5a8e7e.png)

**Comment by jobannon** [comment] 2019-12-16 06:17
![image](https://user-images.githubusercontent.com/16090626/70883711-203fea00-1f91-11ea-8850-f2624cab1e9a.png)

**Comment by jobannon** [comment] 2019-12-16 06:18
health check seems ok-ish

**Comment by jobannon** [comment] 2019-12-16 06:18
must be missing something ...I am borrowing this rc file from a friend but Ranger seems to run without issue

**Comment by jobannon** [comment] 2019-12-16 06:19
![image](https://user-images.githubusercontent.com/16090626/70883793-57160000-1f91-11ea-927d-4ed9fa9194eb.png)

**Comment by jobannon** [comment] 2019-12-16 06:21
![image](https://user-images.githubusercontent.com/16090626/70883873-93e1f700-1f91-11ea-83b0-c125744c01a3.png)

**Comment by weirongxu** [comment] 2019-12-16 10:20
You haven't provided information about `:CocInfo`

**Comment by weirongxu** [comment] 2019-12-16 10:22
With these messages, I still can't reproduce your bug. Maybe you need to provide a minimal vimrc, like [this](https://github.com/weirongxu/coc-explorer/tree/master/mini_vimrc), otherwise, I'm afraid I can't help you.

**Comment by kristijanhusak** [comment] 2019-12-16 14:30
Same thing happens for me from time to time, but I don't know exact steps to reproduce.

**Comment by jobannon** [comment] 2019-12-16 15:56
'## versions

vim version: NVIM v0.4.3
node version: v13.2.0
coc.nvim version: 0.0.74-bc017b02e6
term: iTerm.app
platform: darwin

## Messages

## Output channel: explorer


## Output channel: snippets
[Info  - 8:55:09 AM] watchman watching project: /Users/josho/.config/coc/ultisnips
[Info  - 8:55:09 AM] subscribing "**/*.snippets" in /Users/josho/.config/coc/ultisnips
'

**Comment by jobannon** [comment] 2019-12-16 15:56
Sorry - please find above

**Comment by jobannon** [comment] 2019-12-16 16:50
![out2](https://user-images.githubusercontent.com/16090626/70926001-89ebe280-1fe9-11ea-95fc-372f626021a9.gif)

**Comment by weirongxu** [comment] 2019-12-17 02:41
It looks like some plugins or configurations executed the `:syntax on`, caused the highlighting to be deleted.

**Comment by nineser** [comment] 2019-12-17 06:25
`source $MYVIMRC`.

After running this command, this problem will occur

**Comment by kristijanhusak** [comment] 2019-12-17 22:22
Just a note that this still happens for me, especially when i source $MYVIMRC.

**Comment by weirongxu** [comment] 2019-12-18 04:13
> Just a note that this still happens for me, especially when i source $MYVIMRC.

Have you try to reopen the `explorer` buffer?

**Comment by kristijanhusak** [comment] 2019-12-18 09:03
Yeah, not helping.

![screen](https://user-images.githubusercontent.com/1782860/71071836-a02aa780-217d-11ea-8056-dac506026ebd.gif)

**Comment by weirongxu** [comment] 2019-12-18 09:30
Is it because you are using the npm version? There are still has some bugs in the git version, so I have not released yet.

**Comment by kristijanhusak** [comment] 2019-12-18 09:33
Yeah, I did 'CocUninstall coc-explorer' and then 'CocInstall coc-explorer'. Thought that will install the latest version.
Ok, my bad then.

**Comment by weirongxu** [comment] 2019-12-18 09:48
Never mind, I thought you knew it's not the same.

**Comment by mtjn** [comment] 2019-12-22 09:53
I am having the same issue, but I find that the first time i open the explorer, it is blank. If I then close and reopen, I see the same type of output as the other users here

**Comment by weirongxu** [comment] 2019-12-23 04:07
Should be fixed in the latest released version

**Closed by weirongxu** 2019-12-23 04:07 UTC
Labels: bug

**Comment by hujianxin** [comment] 2020-01-18 07:04
I preduced this issue by install 'Yggdroot/indentLine'

**Comment by hujianxin** [comment] 2020-01-18 07:06
adding this line to vimrc `let g:indentLine_char = '│'` will repreduce this issue

**Comment by weirongxu** [comment] 2020-01-18 08:48
> I preduced this issue by install 'Yggdroot/indentLine'

use `g:indentLine_fileTypeExclude` to avoid this

**Comment by hujianxin** [comment] 2020-01-18 10:14
@weirongxu thanks
