### ISSUE TITLE
Maybe coc-explorer has some crash in neovim-nightly.

### ISSUE THREAD

**Issue by 66RING** [weirongxu/coc-explorer#264] opened 2020-09-09 14:22 UTC
Hello,

When I upgrade neovim to nightly(v0.5.0-677-g59712f6db), I found that my vim often exit with some error.

And if I dont use explorer at all, that will not happen. I dont know if that is a explorer bug. 

```shell
NVIM v0.5.0-677-g59712f6db
Build type: RelWithDebInfo
LuaJIT 2.0.5
```

**Comment by weirongxu** [comment] 2020-09-09 14:24
Duplicate of #262

**Comment by weirongxu** [comment] 2020-09-09 14:24
Fixed in the latest version

**Closed by weirongxu** 2020-09-09 14:24 UTC
Labels: bug
