### ISSUE TITLE
[BUG]how can i use the icons for the coc-explorer?

### ISSUE THREAD

**Issue by auqf** [weirongxu/coc-explorer#581] opened 2024-01-02 01:48 UTC
![image](https://github.com/weirongxu/coc-explorer/assets/8895540/b78389a4-6a34-4148-b122-652ffaec29b6)
how to use the icon for the cocExplorer?
why the icon cannot display? the config as follows:
![image](https://github.com/weirongxu/coc-explorer/assets/8895540/27ff0d0f-02a5-4195-b106-0687fdb0dab7)

**Comment by weirongxu** [comment] 2024-01-02 02:37
Duplicate of https://github.com/weirongxu/coc-explorer/issues/483

**Closed** 2024-01-02 02:37 UTC
Labels: bug
