### ISSUE TITLE
Buffer has ~1 second delay when opening on startup.

### ISSUE THREAD

**Issue by kilian544** [weirongxu/coc-explorer#268] opened 2020-09-11 23:54 UTC
I have an augroup to open coc-explorer on startup, yet I have to wait ~1 second before the buffer opens. When just using the bound command I experience the same problem. Any toggling of coc-explorer after this is instant.
So I am guessing it has to do with some initialization?

Augroup:
`augroup ProjectDrawer
  autocmd!
  autocmd VimEnter * :CocCommand explorer
augroup END
`
Bind:
`nmap <leader>ee :CocCommand explorer<cr>
`

Any ideas?

**Comment by weirongxu** [comment] 2020-09-12 02:49
This is by design because I added 500 milliseconds for debouncing, I may try to cut the debounce time in the future

https://github.com/weirongxu/coc-explorer/blob/847f480a3de6d34c79594caa6c972ecca4e2adba/src/source/sources/buffer/bufferSource.ts#L79

**Comment by kilian544** [comment] 2020-09-12 13:09
Are you positive about this? I tried building the extension myself and playing around with the value, result seems the same. I even tried using throttle instead of debounce since throttle immediatly triggers once, thinking that might stop the delay for the first time, not positive about that though.

Given I might just be a monkey goofing something up. I ":CocUninstalled" your plugin, downloaded the git and "npm run built" it. Added the directory to the vim runtimepath and everything appears to work as expected. Yet the lag persists...

I tried to change the debounce values from 50 through 10000 and throtte them, but the behaviour does not seem to change.

Thanks for your time! And please, do not feel obliged to put any more time into this than you find interesing! If you don't feel like helping my with this that is totally fine!

**Comment by weirongxu** [comment] 2020-09-18 18:31
Although I don’t have time to dig deep yet, I will back to see this after I implement other features in the future.

**Comment by iamcco** [comment] 2020-09-24 06:53
I thinks the 1 second delay is expected behavior since it's an coc.nvim extension and it have to wait the coc.nvim startup to load the extension and then  the command `explorer` will be run after that.

**Comment by weirongxu** [comment] 2020-09-24 07:13
@iamcco is right. Seems it won't be fixed because coc.nvim is asynchronous.

So I close this, of course, if there is a solution, I will reconsider in the future

**Closed by weirongxu** 2020-09-24 07:13 UTC
Labels: enhancement, optimization

**Comment by bboyadao** [comment] 2022-01-24 22:26
this anoying. maybe i will back to :ex
