### ISSUE TITLE
Enable coc-explorer when opening a directory

### ISSUE THREAD

**Issue by gregorywaynepower** [weirongxu/coc-explorer#290] opened 2020-10-19 16:42 UTC
Hey Everyone,

I may have missed this in the documentation, but it is unclear to me where I can enable coc-explorer as the default directory explorer when I select a directory. I'm trying to switch from Nerdtree that has this enabled by default.

Thank you,

**Comment by weirongxu** [comment] 2020-10-19 17:14
Duplicate of #123

**Closed by weirongxu** 2020-10-19 17:14 UTC
Labels: feature_request
