### ISSUE TITLE
Option to not select explorer when opened

### ISSUE THREAD

**Issue by Rizhiy** [weirongxu/coc-explorer#237] opened 2020-07-22 16:16 UTC
Hi, I want to automatically open the explorer when vim starts, but keep the focus on original file.
Currently, when I open explorer it automatically grabs focus.

I tried different options of `--open-action-strategy`, but none of them seem to change the behaviour.

**Comment by weirongxu** [comment] 2020-07-23 02:20
Duplicate of #120

**Closed by weirongxu** 2020-07-23 02:20 UTC
Labels: feature_request
