### ISSUE TITLE
Refreshing explorer if files were added/deleted externally

### ISSUE THREAD

**Issue by daedsidog** [weirongxu/coc-explorer#395] opened 2021-02-23 21:28 UTC
Currently if I add files to the workspace manually using shell, `coc-explorer` will not recognise them until I refresh manually.

This is despite having `autocmd User CocDiagnosticChange,CocGitStatusChange call CocActionAsync('runCommand', 'explorer.doAction', 'closest', ['refresh'])
` in my `.vimrc`.

**Comment by weirongxu** [comment] 2021-02-24 04:20
Duplicate of #161

**Closed by weirongxu** 2021-02-24 04:20 UTC
