### ISSUE TITLE
Icons in coc-explorer get cut off

### ISSUE THREAD

**Issue by ayushsherpa111** [weirongxu/coc-explorer#295] opened 2020-10-26 06:51 UTC
I am not sure if this is an issue with coc-explorer but the icons get cut off
![image](https://user-images.githubusercontent.com/35552818/97141887-b767f780-1787-11eb-8eb7-f38ac63c9e60.png)
i tried several config commands like `explorer.file.child.template` or `explorer.file.column.indent.chars` but none worked.

**Comment by weirongxu** [comment] 2020-10-26 08:00
Duplicate of #200

**Closed by weirongxu** 2020-10-26 08:00 UTC
Labels: bug
