### ISSUE TITLE
Is there a way to shorten the filename with three dots?

### ISSUE THREAD

**Issue by svanharmelen** [weirongxu/coc-explorer#358] opened 2021-01-05 16:58 UTC
I have the git and diagnostic status set to the right, but then on long filenames the go off screen. Is there an option to get it like this:

<img width="219" alt="image" src="https://user-images.githubusercontent.com/4171547/103674867-8a9e4080-4f7f-11eb-8c17-427bdfbcd502.png">

So that the filename is shortened in favor of the diag and git info?

**Comment by weirongxu** [comment] 2021-01-06 04:23
Duplicate of #329

**Closed by weirongxu** 2021-01-06 04:23 UTC
Labels: question

**Comment by svanharmelen** [comment] 2021-01-06 08:42
Thanks for you reply @weirongxu, but this isn't the same question as was asked in #329. I did find that issue and also used it to configure the explorer. I works perfectly, but it doesn't add any dots to shorten long filenames:

<img width="221" alt="image" src="https://user-images.githubusercontent.com/4171547/103747653-43599380-5003-11eb-9832-7f1c8ac2a4b0.png">

As you can see everything is nicely aligned, but the second filename is not shortened. Any thing I missed? the config I used for this part is:

```
  "explorer.contentWidthType": "win-width",
  "explorer.file.child.template": "[selection | clip | 1][indent][icon | 1] [filename growRight 1] [diagnosticError | diagnosticWarning][git]",
```

**Comment by weirongxu** [comment] 2021-01-06 10:00
> Thanks for you reply @weirongxu, but this isn't the same question as was asked in #329. I did find that issue and also used it to configure the explorer. I works perfectly, but it doesn't add any dots to shorten long filenames:
> 
> <img alt="image" width="221" src="https://user-images.githubusercontent.com/4171547/103747653-43599380-5003-11eb-9832-7f1c8ac2a4b0.png">
> 
> As you can see everything is nicely aligned, but the second filename is not shortened. Any thing I missed? the config I used for this part is:
> 
> ```
>   "explorer.contentWidthType": "win-width",
>   "explorer.file.child.template": "[selection | clip | 1][indent][icon | 1] [filename growRight 1] [diagnosticError | diagnosticWarning][git]",
> ```

`[filename growRight 1 omitRight 1]`

**Comment by svanharmelen** [comment] 2021-01-06 10:15
Super nice! Works like a charm 👍🏻  Thanks!
