### ISSUE TITLE
 Icon not showing

### ISSUE THREAD

**Issue by TENX-S** [weirongxu/coc-explorer#507] opened 2022-01-28 13:12 UTC
![image](https://user-images.githubusercontent.com/40336192/151552406-2187469d-e3ef-4dd9-b7ee-6fdf8329d302.png)
I guess the icon is shown by default? May I missed something.

**Comment by weirongxu** [comment] 2022-01-28 14:20
Duplicate of #483

**Closed by weirongxu** 2022-01-28 14:20 UTC
