### ISSUE TITLE
Nvim crushes on opening a python file

### ISSUE THREAD

**Issue by anstadnik** [weirongxu/coc-explorer#263] opened 2020-09-08 07:20 UTC
When I open a python file with the latest neovim it crashes.
For debugging purposes I built the last nightly neovim in debug mode.
`neovim --version`
```
NVIM v0.5.0-672-gd8e6a0396
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/tmp/neovim/build/config -I/tmp/neovim/src -I/tmp/neovim/.deps/usr/include -I/usr/include -I/tmp/neovim/build/src/nvim/auto -I/tmp/neovim/build/include
Compiled by astadnik@astadnik

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
Sufficient init.vim
```
call plug#begin()
Plug 'neoclide/coc.nvim',      { 'do': 'yarn install --frozen-lockfile' }
let g:coc_global_extensions = ['coc-explorer']
noremap <C-n> :CocCommand explorer<CR>
call plug#end()
```
[Asciinema recording just for fun](https://asciinema.org/a/muCUcvH03SFRCkgVolzmBgNwb).

Backtrace created by running
```
2>&1 coredumpctl -1 gdb | tee -a bt.txt
thread apply all bt full
```
[bt.txt](https://github.com/weirongxu/coc-explorer/files/5186667/bt.txt)

**Comment by weirongxu** [comment] 2020-09-08 07:42
Thank you for the information. It maybe a bug of nvim. This problem may occur when call `nvim_buf_add_highlight` by `nvim_call_atomic` and inside the `autocmd BufEnter *`

**Comment by weirongxu** [comment] 2020-09-08 07:43
Duplicate of #262

**Closed** 2020-09-08 15:25 UTC
Labels: bug
