### ISSUE TITLE
open file using relative path instead of absolute (full) path

### ISSUE THREAD

**Issue by pirey** [weirongxu/coc-explorer#349] opened 2020-12-27 13:00 UTC
Hi, when I open a file from the explorer, and run `echo expand('%')` it displays absolute (full) path instead of relative path from current working directory.

![image](https://user-images.githubusercontent.com/10344542/103171331-0c0a1a80-487e-11eb-9a4d-62d2fd4997b0.png)

I need to display the filename in my statusline / tabline, and absolute path is usually too long.

How can I achieve this?

Thanks.

**Comment by weirongxu** [comment] 2020-12-27 13:10
Duplicate of #328

**Closed by weirongxu** 2020-12-27 13:10 UTC
